/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('dance_moves').del()
  await knex('dance_moves').insert([
    {
      id: 1,
      name: 'Open Hold',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 2,
      name: 'Closed Hold',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Open hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: 'Back to Back',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 4,
      name: 'Quarter Turns',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 5,
      name: 'Dile Que No',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 6,
      name: 'Dile Que Si',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 7,
      name: 'Por Fuera',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 8,
      name: 'Enchufla',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 9,
      name: 'Enchufla Doble',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 10,
      name: 'Enchufla con Vuelta',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 11,
      name: 'Exhibela',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 12,
      name: 'Exhibela Doble',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 13,
      name: 'El Uno',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 14,
      name: 'Kentucky',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 15,
      name: 'Sombrero (Rapido)',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 16,
      name: 'Enchufla con Coca Cola',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 17,
      name: "Pa'al Medio",
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 18,
      name: 'Dame',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 19,
      name: 'Un Tarro',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 20,
      name: 'Un Tarro de Mentira',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 21,
      name: 'Mosquito',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: 'Pise',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: 'Fly',
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: "Caminamos pa'aariva",
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: "Caminamos pa'abajo",
      level: 'Beginner',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
  ])
}
