/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('dance_moves').del()
  await knex('dance_moves').insert([
    {
      id: 91,
      style_id: 1,
      name: 'Abanico',
      level: 'Intermediate',
      synonyms: 'Fan',
      translation: 'Abanico',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Fan-like motion',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the fan movements.',
      instructions_lead: 'Lead the fan style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 92,
      style_id: 1,
      name: 'Amistad',
      level: 'Intermediate',
      synonyms: 'Friendship',
      translation: 'Amistad',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Friend-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Social Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the friendship lead.',
      instructions_lead: 'Guide through the friendship style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 93,
      style_id: 1,
      name: 'Babosa',
      level: 'Intermediate',
      synonyms: 'Slug',
      translation: 'Babosa',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Slug-like movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the slug movements.',
      instructions_lead: 'Lead the slug style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 94,
      style_id: 1,
      name: 'Cadena',
      level: 'Intermediate',
      synonyms: 'Chain',
      translation: 'Cadena',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Chain-like motion',
      based_on: 'Basic Step',
      similar_to: 'Connected Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the chain movements.',
      instructions_lead: 'Guide through the chain style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 95,
      style_id: 1,
      name: 'Coca Cola',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Coca Cola',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Coca Cola-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Coca Cola movements.',
      instructions_lead: 'Lead the Coca Cola style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 96,
      style_id: 1,
      name: 'Coca Cola al Reves',
      level: 'Intermediate',
      synonyms: 'Coca Cola Backwards',
      translation: 'Coca Cola al Reves',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Reverse Coca Cola movement',
      based_on: 'Coca Cola',
      similar_to: 'Reverse Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the reverse Coca Cola lead.',
      instructions_lead: 'Guide through the reverse style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 97,
      style_id: 1,
      name: 'Coca Cola con Vacilala',
      level: 'Intermediate',
      synonyms: 'Coca Cola with Show Off',
      translation: 'Coca Cola con Vacilala',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Coca Cola with show-off motion',
      based_on: 'Coca Cola',
      similar_to: 'Show Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the combined movements.',
      instructions_lead: 'Lead through the Coca Cola with show-off style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 98,
      style_id: 1,
      name: 'Cuban Guapea',
      level: 'Intermediate',
      synonyms: 'Cuban Basic Step',
      translation: 'Cuban Guapea',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Cuban-style movement',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Follow the Cuban Guapea lead.',
      instructions_lead: 'Guide through the Cuban style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 99,
      style_id: 1,
      name: 'Dame con manos',
      level: 'Intermediate',
      synonyms: 'Give with Hands',
      translation: 'Dame con manos',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Hand movements included',
      based_on: 'Dame',
      similar_to: 'Hand Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the hand movements.',
      instructions_lead: 'Lead with the hand style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 100,
      style_id: 1,
      name: 'Dame De Mentira',
      level: 'Intermediate',
      synonyms: 'Fake Give',
      translation: 'Dame De Mentira',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Fake giving motion',
      based_on: 'Dame',
      similar_to: 'Fake Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the fake give lead.',
      instructions_lead: 'Guide through the fake style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 101,
      style_id: 1,
      name: 'Dame dos con Giro',
      level: 'Intermediate',
      synonyms: 'Give Two with Turn',
      translation: 'Dame dos con Giro',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Two gives with a turn',
      based_on: 'Dame',
      similar_to: 'Turn Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the two give movements.',
      instructions_lead: 'Lead through the two gives effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 102,
      style_id: 1,
      name: 'Danilo',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Danilo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Danilo-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Danilo movements.',
      instructions_lead: 'Guide through the Danilo style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 103,
      style_id: 1,
      name: 'Dedo Guarapo y Bota',
      level: 'Intermediate',
      synonyms: 'Finger and Boot',
      translation: 'Dedo Guarapo y Bota',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Finger and boot motion',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the finger and boot movements.',
      instructions_lead: 'Lead through the finger and boot style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 104,
      style_id: 1,
      name: 'Dip',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Dip',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Dipping motion',
      based_on: 'Basic Step',
      similar_to: 'Basic Moves',
      bar_counts: 4,
      instructions_follower: 'Follow the dip lead.',
      instructions_lead: 'Guide through the dipping style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 105,
      style_id: 1,
      name: 'El Dedo',
      level: 'Intermediate',
      synonyms: 'The Finger',
      translation: 'El Dedo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Finger movement',
      based_on: 'Basic Step',
      similar_to: 'Finger Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the finger movements.',
      instructions_lead: 'Lead through the finger style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 106,
      style_id: 1,
      name: 'Enchufala con Bikini',
      level: 'Intermediate',
      synonyms: 'Enchufala with Bikini',
      translation: 'Enchufala con Bikini',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Bikini-style movement',
      based_on: 'Enchufala',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the bikini movements.',
      instructions_lead: 'Lead through the bikini style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 107,
      style_id: 1,
      name: 'Enchufala Con Rueda',
      level: 'Intermediate',
      synonyms: 'Enchufala with Wheel',
      translation: 'Enchufala Con Rueda',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Wheel-like movement',
      based_on: 'Enchufala',
      similar_to: 'Wheel Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the wheel movements.',
      instructions_lead: 'Guide through the wheel style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 108,
      style_id: 1,
      name: 'Espresso',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Espresso',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Espresso-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 4,
      instructions_follower: 'Follow the espresso movements.',
      instructions_lead: 'Guide through the espresso style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 109,
      style_id: 1,
      name: 'Estrella',
      level: 'Intermediate',
      synonyms: 'Star',
      translation: 'Estrella',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Star-like movement',
      based_on: 'Basic Step',
      similar_to: 'Star Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the star movements.',
      instructions_lead: 'Lead through the star style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 110,
      style_id: 1,
      name: 'Fin',
      level: 'Intermediate',
      synonyms: 'End',
      translation: 'Fin',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Ending movement',
      based_on: 'Basic Step',
      similar_to: 'Ending Moves',
      bar_counts: 4,
      instructions_follower: 'Follow the finishing lead.',
      instructions_lead: 'Guide through the finishing style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 111,
      style_id: 1,
      name: 'Flamenco',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Flamenco',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Flamenco-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the flamenco movements.',
      instructions_lead: 'Lead through the flamenco style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 112,
      style_id: 1,
      name: 'La Familia',
      level: 'Intermediate',
      synonyms: 'The Family',
      translation: 'La Familia',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Family-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Social Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the family movements.',
      instructions_lead: 'Guide through the family style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 113,
      style_id: 1,
      name: 'Laso',
      level: 'Intermediate',
      synonyms: 'Lasso',
      translation: 'Laso',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Lasso-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the lasso movements.',
      instructions_lead: 'Lead through the lasso style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 114,
      style_id: 1,
      name: 'Ochenta y Ocho',
      level: 'Intermediate',
      synonyms: 'Eighty-Eight',
      translation: 'Ochenta y Ocho',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Eighty-eight count movement',
      based_on: 'Basic Step',
      similar_to: 'Number Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the eighty-eight lead.',
      instructions_lead: 'Lead through the eighty-eight movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 115,
      style_id: 1,
      name: 'Paseala',
      level: 'Intermediate',
      synonyms: 'Walk Her',
      translation: 'Paseala',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Walking movement',
      based_on: 'Basic Step',
      similar_to: 'Walking Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the walking movements.',
      instructions_lead: 'Guide through the walking style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 116,
      style_id: 1,
      name: 'Paseala Arriba',
      level: 'Intermediate',
      synonyms: 'Walk Her Up',
      translation: 'Paseala Arriba',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Upward walking motion',
      based_on: 'Paseala',
      similar_to: 'Walking Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the upward walking movements.',
      instructions_lead: 'Lead through the upward style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 117,
      style_id: 1,
      name: 'Patin',
      level: 'Intermediate',
      synonyms: 'Skate',
      translation: 'Patin',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Skating motion',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the skating movements.',
      instructions_lead: 'Guide through the skating style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 118,
      style_id: 1,
      name: 'Patineta',
      level: 'Intermediate',
      synonyms: 'Skateboard',
      translation: 'Patineta',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Skateboard-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the skateboard movements.',
      instructions_lead: 'Lead through the skateboard style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 119,
      style_id: 1,
      name: 'Reverencia',
      level: 'Intermediate',
      synonyms: 'Reverence',
      translation: 'Reverencia',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Reverence motion',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the reverence movements.',
      instructions_lead: 'Lead through the reverence style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 120,
      style_id: 1,
      name: 'Sencilla Y Enganala',
      level: 'Intermediate',
      synonyms: 'Simple and Hook',
      translation: 'Sencilla Y Enganala',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Simple and hook movement',
      based_on: 'Basic Step',
      similar_to: 'Hook Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the simple and hook movements.',
      instructions_lead: 'Guide through the combined style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 121,
      style_id: 1,
      name: 'Setenta',
      level: 'Intermediate',
      synonyms: 'Seventy',
      translation: 'Setenta',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Seventy count movement',
      based_on: 'Basic Step',
      similar_to: 'Number Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the seventy lead.',
      instructions_lead: 'Lead through the seventy movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 122,
      style_id: 1,
      name: 'Setenta y Cinco',
      level: 'Intermediate',
      synonyms: 'Seventy-Five',
      translation: 'Setenta y Cinco',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Seventy-five count movement',
      based_on: 'Basic Step',
      similar_to: 'Number Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the seventy-five lead.',
      instructions_lead: 'Lead through the seventy-five movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 123,
      style_id: 1,
      name: 'Siete con Coca Cola',
      level: 'Intermediate',
      synonyms: 'Seven with Coca Cola',
      translation: 'Siete con Coca Cola',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Seven count with Coca Cola',
      based_on: 'Siete',
      similar_to: 'Number Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the seven with Coca Cola lead.',
      instructions_lead: 'Lead through the combined movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 124,
      style_id: 1,
      name: 'Siete Moderno',
      level: 'Intermediate',
      synonyms: 'Modern Seven',
      translation: 'Siete Moderno',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Modern seven count movement',
      based_on: 'Siete',
      similar_to: 'Modern Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the modern seven lead.',
      instructions_lead: 'Lead through the modern movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 125,
      style_id: 1,
      name: 'Sombrero',
      level: 'Intermediate',
      synonyms: 'Hat',
      translation: 'Sombrero',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Hat-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the hat movements.',
      instructions_lead: 'Lead through the hat style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 126,
      style_id: 1,
      name: 'Sombrero Mambo',
      level: 'Intermediate',
      synonyms: 'Mambo Hat',
      translation: 'Sombrero Mambo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Mambo-style hat movement',
      based_on: 'Sombrero',
      similar_to: 'Mambo Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the mambo hat movements.',
      instructions_lead: 'Lead through the mambo style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 127,
      style_id: 1,
      name: 'Tight Turn',
      level: 'Intermediate',
      synonyms: 'N/A',
      translation: 'Tight Turn',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Tight turn movement',
      based_on: 'Basic Step',
      similar_to: 'Turn Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the tight turn lead.',
      instructions_lead: 'Guide through the tight turn style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 128,
      style_id: 1,
      name: 'Tumba Francesa',
      level: 'Intermediate',
      synonyms: 'French Fall',
      translation: 'Tumba Francesa',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'French fall movement',
      based_on: 'Basic Step',
      similar_to: 'Fall Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the French fall movements.',
      instructions_lead: 'Lead through the French fall style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 129,
      style_id: 1,
      name: 'Vacilala con Engano',
      level: 'Intermediate',
      synonyms: 'Show Off with Trick',
      translation: 'Vacilala con Engano',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Trick show-off movement',
      based_on: 'Vacilala',
      similar_to: 'Show Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the trick movements.',
      instructions_lead: 'Guide through the trick style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 130,
      style_id: 1,
      name: 'Vacilala Entrada',
      level: 'Intermediate',
      synonyms: 'Show Off Entrance',
      translation: 'Vacilala Entrada',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Entrance show-off movement',
      based_on: 'Vacilala',
      similar_to: 'Entrance Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the entrance movements.',
      instructions_lead: 'Lead through the entrance style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 131,
      style_id: 1,
      name: 'Vacilala Sentada',
      level: 'Intermediate',
      synonyms: 'Show Off Sitting',
      translation: 'Vacilala Sentada',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in a seated position',
      contains: 'Sitting show-off movement',
      based_on: 'Vacilala',
      similar_to: 'Seated Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the seated movements.',
      instructions_lead: 'Lead through the seated style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
  ])
}
