/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('dance_moves').del()
  await knex('dance_moves').insert([
    {
      id: 132,
      style_id: 1,
      name: 'Abrazala',
      level: 'Advanced',
      synonyms: 'Embrace Her',
      translation: 'Abrazala',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Embrace-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the embrace movements.',
      instructions_lead: 'Lead through the embrace style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 133,
      style_id: 1,
      name: 'Amistad y Vete',
      level: 'Advanced',
      synonyms: 'Friendship and Go',
      translation: 'Amistad y Vete',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Friendship-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Social Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the friendship movements.',
      instructions_lead: 'Lead through the friendship style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 134,
      style_id: 1,
      name: 'Arcoiris',
      level: 'Advanced',
      synonyms: 'Rainbow',
      translation: 'Arcoiris',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Rainbow-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the rainbow movements.',
      instructions_lead: 'Lead through the rainbow style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 135,
      style_id: 1,
      name: 'Around The World',
      level: 'Advanced',
      synonyms: 'Global Dance',
      translation: 'Around The World',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Circular movement',
      based_on: 'Basic Step',
      similar_to: 'Global Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the world movements.',
      instructions_lead: 'Lead around the world effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 136,
      style_id: 1,
      name: 'Azuquita',
      level: 'Advanced',
      synonyms: 'Little Sugar',
      translation: 'Azuquita',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Sweet-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the sweet movements.',
      instructions_lead: 'Lead through the sweet style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 137,
      style_id: 1,
      name: 'Babosa Doble',
      level: 'Advanced',
      synonyms: 'Double Snail',
      translation: 'Babosa Doble',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Double snail movement',
      based_on: 'Babosa',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the double snail movements.',
      instructions_lead: 'Lead through the double style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 138,
      style_id: 1,
      name: 'Bacardi Limon',
      level: 'Advanced',
      synonyms: 'Lemon Bacardi',
      translation: 'Bacardi Limon',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Bacardi-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Bacardi movements.',
      instructions_lead: 'Lead through the Bacardi style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 139,
      style_id: 1,
      name: 'Balsero',
      level: 'Advanced',
      synonyms: 'Rafting',
      translation: 'Balsero',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Rafting-style movement',
      based_on: 'Basic Step',
      similar_to: 'Water Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the rafting movements.',
      instructions_lead: 'Lead through the rafting style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 140,
      style_id: 1,
      name: 'Bayamo',
      level: 'Advanced',
      synonyms: 'N/A',
      translation: 'Bayamo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Bayamo-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Bayamo movements.',
      instructions_lead: 'Lead through the Bayamo style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 141,
      style_id: 1,
      name: 'Bayamo por Abajo',
      level: 'Advanced',
      synonyms: 'Bayamo Down',
      translation: 'Bayamo por Abajo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Bayamo downward movement',
      based_on: 'Bayamo',
      similar_to: 'Downward Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the downward Bayamo movements.',
      instructions_lead: 'Lead through the downward style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 142,
      style_id: 1,
      name: 'Bebe',
      level: 'Advanced',
      synonyms: 'Drink',
      translation: 'Bebe',
      move_type: 'Couple',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Drink-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 9,
      instructions_follower: 'Follow the drink movements.',
      instructions_lead: 'Lead through the drink style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 143,
      style_id: 1,
      name: 'Beso',
      level: 'Advanced',
      synonyms: 'Kiss',
      translation: 'Beso',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Kiss-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the kiss movements.',
      instructions_lead: 'Lead through the kiss style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 144,
      style_id: 1,
      name: 'Candado Complicado',
      level: 'Advanced',
      synonyms: 'Complicated Lock',
      translation: 'Candado Complicado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in locked position',
      contains: 'Complicated locking movement',
      based_on: 'Candado',
      similar_to: 'Lock Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the complicated lock movements.',
      instructions_lead: 'Lead through the complicated style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 145,
      style_id: 1,
      name: 'Coca Cola Por Atras',
      level: 'Advanced',
      synonyms: 'Coca Cola Back',
      translation: 'Coca Cola Por Atras',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Coca Cola backward movement',
      based_on: 'Coca Cola',
      similar_to: 'Backward Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Coca Cola backward movements.',
      instructions_lead: 'Lead through the backward style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 146,
      style_id: 1,
      name: 'Colon con Amiga',
      level: 'Advanced',
      synonyms: 'Colon with Friend',
      translation: 'Colon con Amiga',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Colon-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Social Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the colon movements.',
      instructions_lead: 'Lead through the colon style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 147,
      style_id: 1,
      name: 'Consorte',
      level: 'Advanced',
      synonyms: 'Consort',
      translation: 'Consorte',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Consort-style movement',
      based_on: 'Basic Step',
      similar_to: 'Social Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the consort movements.',
      instructions_lead: 'Lead through the consort style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 148,
      style_id: 1,
      name: 'Copelia',
      level: 'Advanced',
      synonyms: 'N/A',
      translation: 'Copelia',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Copelia-style movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Copelia movements.',
      instructions_lead: 'Lead through the Copelia style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 149,
      style_id: 1,
      name: 'Copelia Complicado',
      level: 'Advanced',
      synonyms: 'Complicated Copelia',
      translation: 'Copelia Complicado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Complicated Copelia movement',
      based_on: 'Copelia',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the complicated Copelia movements.',
      instructions_lead: 'Lead through the complicated style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 150,
      style_id: 1,
      name: 'Cuarenta y Cinco',
      level: 'Advanced',
      synonyms: 'Forty-Five',
      translation: 'Cuarenta y Cinco',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Forty-five themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the forty-five movements.',
      instructions_lead: 'Lead through the forty-five style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 151,
      style_id: 1,
      name: 'Dame Elegante',
      level: 'Advanced',
      synonyms: 'Elegant Give',
      translation: 'Dame Elegante',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Elegant give movement',
      based_on: 'Dame',
      similar_to: 'Elegant Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the elegant movements.',
      instructions_lead: 'Lead through the elegant style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 152,
      style_id: 1,
      name: 'Dedo Loco',
      level: 'Advanced',
      synonyms: 'Crazy Finger',
      translation: 'Dedo Loco',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Crazy finger movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the crazy finger movements.',
      instructions_lead: 'Lead through the crazy style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 153,
      style_id: 1,
      name: 'El Atrevido',
      level: 'Advanced',
      synonyms: 'The Daring',
      translation: 'El Atrevido',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Daring movement',
      based_on: 'Basic Step',
      similar_to: 'Daring Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the daring movements.',
      instructions_lead: 'Lead through the daring style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 154,
      style_id: 1,
      name: 'El Clasico',
      level: 'Advanced',
      synonyms: 'The Classic',
      translation: 'El Clasico',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Classic movement',
      based_on: 'Basic Step',
      similar_to: 'Classic Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the classic movements.',
      instructions_lead: 'Lead through the classic style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 155,
      style_id: 1,
      name: 'El Dedo Complicado',
      level: 'Advanced',
      synonyms: 'Complicated Finger',
      translation: 'El Dedo Complicado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Complicated finger movement',
      based_on: 'Dedo',
      similar_to: 'Finger Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the complicated finger movements.',
      instructions_lead: 'Lead through the complicated style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 156,
      style_id: 1,
      name: 'El Dedo Saboreado',
      level: 'Advanced',
      synonyms: 'Savored Finger',
      translation: 'El Dedo Saboreado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Savored finger movement',
      based_on: 'Dedo',
      similar_to: 'Finger Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the savored finger movements.',
      instructions_lead: 'Lead through the savored style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 157,
      style_id: 1,
      name: 'El Doce',
      level: 'Advanced',
      synonyms: 'The Twelve',
      translation: 'El Doce',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Twelve-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the twelve movements.',
      instructions_lead: 'Lead through the twelve style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 158,
      style_id: 1,
      name: 'El Dos',
      level: 'Advanced',
      synonyms: 'The Two',
      translation: 'El Dos',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Two-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the two movements.',
      instructions_lead: 'Lead through the two style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 159,
      style_id: 1,
      name: 'El Nino',
      level: 'Advanced',
      synonyms: 'The Boy',
      translation: 'El Nino',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Boy-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the boy movements.',
      instructions_lead: 'Lead through the boy style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 160,
      style_id: 1,
      name: 'El Salao',
      level: 'Advanced',
      synonyms: 'The Unlucky',
      translation: 'El Salao',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Unlucky-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the unlucky movements.',
      instructions_lead: 'Lead through the unlucky style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 161,
      style_id: 1,
      name: 'El Suave',
      level: 'Advanced',
      synonyms: 'The Smooth',
      translation: 'El Suave',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Smooth movement',
      based_on: 'Basic Step',
      similar_to: 'Smooth Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the smooth movements.',
      instructions_lead: 'Lead through the smooth style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 162,
      style_id: 1,
      name: 'Enchufala con Trompo',
      level: 'Advanced',
      synonyms: 'Enchufala with Spin',
      translation: 'Enchufala con Trompo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Enchufala with spinning movement',
      based_on: 'Enchufala',
      similar_to: 'Spinning Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the spinning movements.',
      instructions_lead: 'Lead through the spinning style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 163,
      style_id: 1,
      name: 'Enchufala Doble Largo',
      level: 'Advanced',
      synonyms: 'Double Long Enchufala',
      translation: 'Enchufala Doble Largo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Double long enchufala movement',
      based_on: 'Enchufala',
      similar_to: 'Long Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the double long movements.',
      instructions_lead: 'Lead through the double long style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 164,
      style_id: 1,
      name: 'Enroscate',
      level: 'Advanced',
      synonyms: 'Twist',
      translation: 'Enroscate',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Twisting movement',
      based_on: 'Basic Step',
      similar_to: 'Twist Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the twisting movements.',
      instructions_lead: 'Lead through the twisting style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 165,
      style_id: 1,
      name: 'Festival Carnaval',
      level: 'Advanced',
      synonyms: 'Carnival Festival',
      translation: 'Festival Carnaval',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Carnival-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Festival Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the carnival movements.',
      instructions_lead: 'Lead through the carnival style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 166,
      style_id: 1,
      name: 'Gancho de Ariel',
      level: 'Advanced',
      synonyms: "Ariel's Hook",
      translation: 'Gancho de Ariel',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: "Ariel's hook movement",
      based_on: 'Basic Step',
      similar_to: 'Hook Moves',
      bar_counts: 8,
      instructions_follower: "Follow Ariel's hook movements.",
      instructions_lead: "Lead through Ariel's hook style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 167,
      style_id: 1,
      name: 'Huracan',
      level: 'Advanced',
      synonyms: 'Hurricane',
      translation: 'Huracan',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Hurricane-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Dynamic Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the hurricane movements.',
      instructions_lead: 'Lead through the hurricane style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 168,
      style_id: 1,
      name: 'Juana La Cubana',
      level: 'Advanced',
      synonyms: 'Juana The Cuban',
      translation: 'Juana La Cubana',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Juana-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Cuban Moves',
      bar_counts: 8,
      instructions_follower: "Follow Juana's movements.",
      instructions_lead: "Lead through Juana's style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 169,
      style_id: 1,
      name: 'Kentucky Complicado',
      level: 'Advanced',
      synonyms: 'Complicated Kentucky',
      translation: 'Kentucky Complicado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Complicated Kentucky movement',
      based_on: 'Kentucky',
      similar_to: 'Complex Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the complicated Kentucky movements.',
      instructions_lead: 'Lead through the complicated style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 170,
      style_id: 1,
      name: 'La Blue',
      level: 'Advanced',
      synonyms: 'The Blue',
      translation: 'La Blue',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Blue-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Color Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the blue movements.',
      instructions_lead: 'Lead through the blue style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 171,
      style_id: 1,
      name: 'La Habana',
      level: 'Advanced',
      synonyms: 'The Havana',
      translation: 'La Habana',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Havana-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Cuban Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the Havana movements.',
      instructions_lead: 'Lead through the Havana style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 172,
      style_id: 1,
      name: 'La Jenny',
      level: 'Advanced',
      synonyms: 'N/A',
      translation: 'La Jenny',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Jenny-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: "Follow Jenny's movements.",
      instructions_lead: "Lead through Jenny's style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 173,
      style_id: 1,
      name: 'La Julie',
      level: 'Advanced',
      synonyms: 'N/A',
      translation: 'La Julie',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Julie-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: "Follow Julie's movements.",
      instructions_lead: "Lead through Julie's style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 174,
      style_id: 1,
      name: 'La Sombra',
      level: 'Advanced',
      synonyms: 'The Shadow',
      translation: 'La Sombra',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Shadow-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the shadow movements.',
      instructions_lead: 'Lead through the shadow style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 175,
      style_id: 1,
      name: 'La Tenta',
      level: 'Advanced',
      synonyms: 'The Temptation',
      translation: 'La Tenta',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Temptation-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the temptation movements.',
      instructions_lead: 'Lead through the temptation style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 176,
      style_id: 1,
      name: 'La Vaca',
      level: 'Advanced',
      synonyms: 'The Cow',
      translation: 'La Vaca',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Cow-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the cow movements.',
      instructions_lead: 'Lead through the cow style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 177,
      style_id: 1,
      name: 'Los Encantos',
      level: 'Advanced',
      synonyms: 'The Charms',
      translation: 'Los Encantos',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Charm-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the charm movements.',
      instructions_lead: 'Lead through the charm style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 178,
      style_id: 1,
      name: 'Los Hombres',
      level: 'Advanced',
      synonyms: 'The Men',
      translation: 'Los Hombres',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Men-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the men movements.',
      instructions_lead: 'Lead through the men style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 179,
      style_id: 1,
      name: 'Los Tres',
      level: 'Advanced',
      synonyms: 'The Three',
      translation: 'Los Tres',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Three-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the three movements.',
      instructions_lead: 'Lead through the three style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 180,
      style_id: 1,
      name: 'Luz y Sombra',
      level: 'Advanced',
      synonyms: 'Light and Shadow',
      translation: 'Luz y Sombra',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Light and shadow-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the light and shadow movements.',
      instructions_lead: 'Lead through the light and shadow style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 181,
      style_id: 1,
      name: 'Sabrosura',
      level: 'Advanced',
      synonyms: 'Flavor',
      translation: 'Sabrosura',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Flavor-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the flavor movements.',
      instructions_lead: 'Lead through the flavor style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 182,
      style_id: 1,
      name: 'Saludo',
      level: 'Advanced',
      synonyms: 'Greeting',
      translation: 'Saludo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Greeting-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the greeting movements.',
      instructions_lead: 'Lead through the greeting style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 183,
      style_id: 1,
      name: 'Santiago',
      level: 'Advanced',
      synonyms: 'N/A',
      translation: 'Santiago',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Santiago-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: "Follow Santiago's movements.",
      instructions_lead: "Lead through Santiago's style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 184,
      style_id: 1,
      name: 'Solito',
      level: 'Advanced',
      synonyms: 'Alone',
      translation: 'Solito',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Alone-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the alone movements.',
      instructions_lead: 'Lead through the alone style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 185,
      style_id: 1,
      name: 'Temptacion',
      level: 'Advanced',
      synonyms: 'Temptation',
      translation: 'Temptacion',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Temptation-themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the temptation movements.',
      instructions_lead: 'Lead through the temptation style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 186,
      style_id: 1,
      name: 'Tres con Dedo',
      level: 'Advanced',
      synonyms: 'Three with Finger',
      translation: 'Tres con Dedo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Three with finger movement',
      based_on: 'Basic Step',
      similar_to: 'Finger Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the three with finger movements.',
      instructions_lead:
        'Lead through the three with finger style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 187,
      style_id: 1,
      name: 'Tres Y Uno',
      level: 'Advanced',
      synonyms: 'Three and One',
      translation: 'Tres Y Uno',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Three and one themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the three and one movements.',
      instructions_lead: 'Lead through the three and one style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 188,
      style_id: 1,
      name: 'Tres Y Dos',
      level: 'Advanced',
      synonyms: 'Three and Two',
      translation: 'Tres Y Dos',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Three and two themed movement',
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the three and two movements.',
      instructions_lead: 'Lead through the three and two style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 189,
      style_id: 1,
      name: 'Usted no Puede',
      level: 'Advanced',
      synonyms: "You Can't",
      translation: 'Usted no Puede',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: "You can't themed movement",
      based_on: 'Basic Step',
      similar_to: 'Unique Moves',
      bar_counts: 8,
      instructions_follower: "Follow the you can't movements.",
      instructions_lead: "Lead through the you can't style effectively.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 190,
      style_id: 1,
      name: 'Zarandear',
      level: 'Advanced',
      synonyms: 'Shake',
      translation: 'Zarandear',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Shaking movement',
      based_on: 'Basic Step',
      similar_to: 'Shake Moves',
      bar_counts: 8,
      instructions_follower: 'Follow the shaking movements.',
      instructions_lead: 'Lead through the shaking style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
  ])
}
