/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('dance_moves').del()
  await knex('dance_moves').insert([
    {
      id: 1,
      style_id: 1,
      name: 'Back Rocks',
      level: 'Beginner',
      synonyms: 'Back Step',
      translation: 'Rocadas Hacia Atrás',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Step back with the right foot',
      contains: 'Weight shift',
      based_on: 'Basic Step',
      similar_to: 'Rock Step',
      bar_counts: 4,
      instructions_follower: 'Shift weight back and forth.',
      instructions_lead: "Guide the follower's movement.",
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 2,
      style_id: 1,
      name: 'Basic Guapea',
      level: 'Beginner',
      synonyms: 'Guapea',
      translation: 'Guapea Básica',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Begin in a closed position',
      contains: 'Side-to-side motion',
      based_on: 'Basic Step',
      similar_to: 'Basic Step',
      bar_counts: 4,
      instructions_follower: 'Step side to side as directed.',
      instructions_lead: 'Lead the movement with clear signals.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 3,
      style_id: 1,
      name: 'Basic Steps',
      level: 'Beginner',
      synonyms: 'Basic Step',
      translation: 'Pasos Básicos',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start with the left foot',
      contains: 'Forward and backward movement',
      based_on: 'Salsa timing',
      similar_to: 'Two-step',
      bar_counts: 4,
      instructions_follower: 'Step forward and back with the lead.',
      instructions_lead: 'Guide the follower through the basic timing.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 4,
      style_id: 1,
      name: 'Closed Position',
      level: 'Beginner',
      synonyms: 'Closed Hold',
      translation: 'Posición Cerrada',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start with arms closed around partner',
      contains: 'Intimate connection',
      based_on: 'Basic Step',
      similar_to: 'Open Position',
      bar_counts: 4,
      instructions_follower: 'Maintain connection and follow the lead.',
      instructions_lead: 'Keep a strong frame with your partner.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 5,
      style_id: 1,
      name: 'Dame',
      level: 'Beginner',
      synonyms: 'Give Me',
      translation: 'Dame',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Initiate from a closed hold',
      contains: 'Turning the follower',
      based_on: 'Basic Step',
      similar_to: 'Cross Body Lead',
      bar_counts: 8,
      instructions_follower: "Turn and follow the lead's direction.",
      instructions_lead: 'Guide the follower through the turn.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 6,
      style_id: 1,
      name: 'Dame Ocaito',
      level: 'Beginner',
      synonyms: 'Give Me Ocaito',
      translation: 'Dame Ocaito',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Begin from a closed position',
      contains: 'Turning while transitioning',
      based_on: 'Dame',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow the lead into the turn.',
      instructions_lead: 'Encourage the follower through the transition.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 7,
      style_id: 1,
      name: 'Dile Que No',
      level: 'Beginner',
      synonyms: 'Say No',
      translation: 'Dile Que No',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Guiding away from partner',
      based_on: 'Basic Step',
      similar_to: 'Open Turn',
      bar_counts: 4,
      instructions_follower: "Follow the lead's direction away.",
      instructions_lead: 'Lead the follower away with a clear signal.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 8,
      style_id: 1,
      name: 'Enchufala',
      level: 'Beginner',
      synonyms: 'Hook her',
      translation: 'Enchúfala',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Begin in a closed position',
      contains: 'Turning motion',
      based_on: 'Basic Step',
      similar_to: 'Cross Body Lead',
      bar_counts: 8,
      instructions_follower: 'Follow the lead into the turn.',
      instructions_lead: 'Guide the follower smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 9,
      style_id: 1,
      name: 'Enchufala Y Dame',
      level: 'Beginner',
      synonyms: 'Hook and Give',
      translation: 'Enchúfala y Dame',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with Enchufala',
      contains: 'Combination of moves',
      based_on: 'Enchufala',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow through the moves as directed.',
      instructions_lead: 'Guide through both Enchufala and Dame.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 10,
      style_id: 1,
      name: 'Ladies Right Turn',
      level: 'Beginner',
      synonyms: 'Right Spin for Ladies',
      translation: 'Giro Derecho para Damas',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Right turn for the follower',
      based_on: 'Basic Step',
      similar_to: 'Right Turn',
      bar_counts: 4,
      instructions_follower: 'Step and pivot right.',
      instructions_lead: 'Encourage the turn with your lead.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 11,
      style_id: 1,
      name: 'Right Turn',
      level: 'Beginner',
      synonyms: 'Right Spin',
      translation: 'Giro Derecho',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Start with a basic step',
      contains: '360-degree turn',
      based_on: 'Basic Step',
      similar_to: 'Ladies Right Turn',
      bar_counts: 4,
      instructions_follower: 'Pivot on your right foot.',
      instructions_lead: 'Lead the follower through the turn.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 12,
      style_id: 1,
      name: 'Side Rocks',
      level: 'Beginner',
      synonyms: 'Side Step',
      translation: 'Rocadas Laterales',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Step to the side',
      contains: 'Side-to-side weight shift',
      based_on: 'Basic Step',
      similar_to: 'Back Rocks',
      bar_counts: 4,
      instructions_follower: 'Shift weight side to side.',
      instructions_lead: 'Guide the follower through the rocks.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 13,
      style_id: 1,
      name: 'Tap',
      level: 'Beginner',
      synonyms: 'Step Tap',
      translation: 'Toque',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Step with the left foot',
      contains: 'Quick tap',
      based_on: 'Basic Step',
      similar_to: 'Pause',
      bar_counts: 2,
      instructions_follower: 'Tap foot without weight shift.',
      instructions_lead: 'Lead the tap with confidence.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 14,
      style_id: 1,
      name: 'Tiempo Espana',
      level: 'Beginner',
      synonyms: 'Spain Timing',
      translation: 'Tiempo España',
      move_type: 'Timing',
      rueda_sign: 'N/A',
      starts_with: 'Basic step to music',
      contains: 'Maintaining rhythm',
      based_on: 'Basic Step',
      similar_to: 'Timing Steps',
      bar_counts: 4,
      instructions_follower: 'Stay in sync with the music.',
      instructions_lead: 'Keep timing consistent.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 15,
      style_id: 1,
      name: 'Vuelta',
      level: 'Beginner',
      synonyms: 'Turn',
      translation: 'Vuelta',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Start in closed position',
      contains: 'Full turn for the follower',
      based_on: 'Dame',
      similar_to: 'Cross Body Lead',
      bar_counts: 8,
      instructions_follower: 'Execute the full turn as led.',
      instructions_lead: 'Guide the follower smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 16,
      style_id: 1,
      name: 'Chaparia',
      level: 'Beginner',
      synonyms: 'N/A',
      translation: 'Chaparía',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Basic side-to-side movement',
      based_on: 'Basic Step',
      similar_to: 'Side Step',
      bar_counts: 4,
      instructions_follower: 'Step side to side, maintaining balance.',
      instructions_lead: 'Guide the follower with your lead.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 17,
      style_id: 1,
      name: 'Coco Y Coquito',
      level: 'Beginner',
      synonyms: 'N/A',
      translation: 'Coco y Coquito',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from basic position',
      contains: 'Rhythmic movement',
      based_on: 'Basic Step',
      similar_to: 'Basic Guapea',
      bar_counts: 4,
      instructions_follower: "Stay close to the lead's movements.",
      instructions_lead: 'Lead the follower smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 18,
      style_id: 1,
      name: 'Dame Con Uno / Dos / Tres',
      level: 'Beginner',
      synonyms: 'Give Me One / Two / Three',
      translation: 'Dame Con Uno / Dos / Tres',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin from closed position',
      contains: 'Sequential giving motion',
      based_on: 'Dame',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow the lead through each count.',
      instructions_lead: 'Lead through each count of the move.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 19,
      style_id: 1,
      name: 'Doble Play',
      level: 'Beginner',
      synonyms: 'Double Play',
      translation: 'Doble Play',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin from a basic step',
      contains: 'Two-part movement',
      based_on: 'Basic Step',
      similar_to: 'Enchufala',
      bar_counts: 8,
      instructions_follower: 'Follow the dual motions.',
      instructions_lead: 'Guide the follower through both parts.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 20,
      style_id: 1,
      name: 'El Cero',
      level: 'Beginner',
      synonyms: 'The Zero',
      translation: 'El Cero',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Unique pattern',
      based_on: 'Basic Step',
      similar_to: 'Basic Step',
      bar_counts: 4,
      instructions_follower: "Follow the lead's movements closely.",
      instructions_lead: 'Execute the pattern clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 21,
      style_id: 1,
      name: 'Enchufala Arriba',
      level: 'Beginner',
      synonyms: 'Hook Up',
      translation: 'Enchúfala Arriba',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Start in closed position',
      contains: 'Upward motion',
      based_on: 'Enchufala',
      similar_to: 'Enchufala',
      bar_counts: 8,
      instructions_follower: 'Follow the upward turn.',
      instructions_lead: 'Lead the upward movement smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 22,
      style_id: 1,
      name: 'Enchufala Complicado',
      level: 'Beginner',
      synonyms: 'Complicated Hook',
      translation: 'Enchúfala Complicado',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Complicated transition',
      based_on: 'Enchufala',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Navigate the complexities of the move.',
      instructions_lead: 'Guide the follower through the transitions.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 23,
      style_id: 1,
      name: 'Enchufala Con Giro',
      level: 'Beginner',
      synonyms: 'Hook with Turn',
      translation: 'Enchúfala Con Giro',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Start from closed position',
      contains: 'Turning element',
      based_on: 'Enchufala',
      similar_to: 'Right Turn',
      bar_counts: 8,
      instructions_follower: 'Execute the turn as led.',
      instructions_lead: 'Lead the turn effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 24,
      style_id: 1,
      name: 'Enchufala con Vuelta',
      level: 'Beginner',
      synonyms: 'Hook with Full Turn',
      translation: 'Enchúfala con Vuelta',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Full turn while hooking',
      based_on: 'Enchufala',
      similar_to: 'Vuelta',
      bar_counts: 8,
      instructions_follower: "Turn while following the lead's direction.",
      instructions_lead: 'Guide through the hook and turn.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 25,
      style_id: 1,
      name: 'Enchufala Doble',
      level: 'Beginner',
      synonyms: 'Double Hook',
      translation: 'Enchúfala Doble',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start with a basic step',
      contains: 'Double hooking motion',
      based_on: 'Enchufala',
      similar_to: 'Doble Play',
      bar_counts: 8,
      instructions_follower: 'Follow through both hooks.',
      instructions_lead: 'Guide through the dual hooks.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 26,
      style_id: 1,
      name: 'Enchufala Par Arriba',
      level: 'Beginner',
      synonyms: 'Upward Hook',
      translation: 'Enchúfala Para Arriba',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Upward motion with hook',
      based_on: 'Enchufala',
      similar_to: 'Enchufala',
      bar_counts: 8,
      instructions_follower: 'Execute the upward movement.',
      instructions_lead: 'Lead into the upward hook smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 27,
      style_id: 1,
      name: 'Enchufala Vampiro',
      level: 'Beginner',
      synonyms: 'Vampire Hook',
      translation: 'Enchúfala Vampiro',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Vampire-style motion',
      based_on: 'Enchufala',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow through the vampire motion.',
      instructions_lead: 'Lead into the vampiro style hook.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 28,
      style_id: 1,
      name: 'Festival Balagan',
      level: 'Beginner',
      synonyms: 'Festival Chaos',
      translation: 'Festival Balagán',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Festival-style chaos',
      based_on: 'Enchufala',
      similar_to: 'Complex Moves',
      bar_counts: 8,
      instructions_follower: 'Navigate the festival chaos.',
      instructions_lead: 'Guide through the chaotic moves.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 29,
      style_id: 1,
      name: 'Festival Dame',
      level: 'Beginner',
      synonyms: 'Festival Give Me',
      translation: 'Festival Dame',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Festival-style giving motion',
      based_on: 'Dame',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow the lead through festival counts.',
      instructions_lead: 'Lead through the festival motions.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 30,
      style_id: 1,
      name: 'Festival Enchufala',
      level: 'Beginner',
      synonyms: 'Festival Hook',
      translation: 'Festival Enchúfala',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Festival hooking motion',
      based_on: 'Enchufala',
      similar_to: 'Enchufala',
      bar_counts: 8,
      instructions_follower: 'Navigate the festival hook.',
      instructions_lead: 'Guide through the festival hooking.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 31,
      style_id: 1,
      name: 'Festival Principe Bueno Malo',
      level: 'Beginner',
      synonyms: 'Good Bad Prince Festival',
      translation: 'Festival Príncipe Bueno Malo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Festival-style prince moves',
      based_on: 'Basic Step',
      similar_to: 'Principe bueno/malo',
      bar_counts: 8,
      instructions_follower: 'Follow through the prince festival moves.',
      instructions_lead: 'Lead the follower through the complexities.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 32,
      style_id: 1,
      name: 'Hombres Derecha / Izquierda',
      level: 'Beginner',
      synonyms: 'Men Right / Left',
      translation: 'Hombres Derecha / Izquierda',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from closed position',
      contains: 'Right and left turns for men',
      based_on: 'Basic Step',
      similar_to: 'Right Turn',
      bar_counts: 8,
      instructions_follower: "Follow the lead's direction.",
      instructions_lead: 'Guide the turns clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 33,
      style_id: 1,
      name: 'Hombres El Centro',
      level: 'Beginner',
      synonyms: 'Men in the Center',
      translation: 'Hombres El Centro',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Center movements for men',
      based_on: 'Basic Step',
      similar_to: 'Cross Body Lead',
      bar_counts: 8,
      instructions_follower: 'Stay in sync with the lead.',
      instructions_lead: 'Guide the center movements.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 34,
      style_id: 1,
      name: 'Hombres Ochenta',
      level: 'Beginner',
      synonyms: 'Men Eight',
      translation: 'Hombres Ochenta',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start with a basic step',
      contains: 'Eight count movements',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 8,
      instructions_follower: 'Follow through the eight counts.',
      instructions_lead: 'Lead through the structured moves.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 35,
      style_id: 1,
      name: 'Hombres Ocho',
      level: 'Beginner',
      synonyms: 'Men Eight Shape',
      translation: 'Hombres Ocho',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Eight shape movements',
      based_on: 'Basic Step',
      similar_to: 'Ocho',
      bar_counts: 8,
      instructions_follower: 'Follow the lead into the eight shape.',
      instructions_lead: 'Guide the eight movements clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 36,
      style_id: 1,
      name: 'Hombres Palmada',
      level: 'Beginner',
      synonyms: 'Men Clap',
      translation: 'Hombres Palmada',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Clapping motion',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Clap while stepping.',
      instructions_lead: 'Lead the clap into the steps.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 37,
      style_id: 1,
      name: 'Hombres Pull',
      level: 'Beginner',
      synonyms: 'Men Pull',
      translation: 'Hombres Pull',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start in closed position',
      contains: 'Pulling motion',
      based_on: 'Basic Step',
      similar_to: 'Dame',
      bar_counts: 8,
      instructions_follower: 'Follow the pulling lead.',
      instructions_lead: 'Guide the follower in the pull.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 38,
      style_id: 1,
      name: 'Hombres Vuelta',
      level: 'Beginner',
      synonyms: 'Men Turn',
      translation: 'Hombres Vuelta',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Start from closed position',
      contains: 'Turning motion for men',
      based_on: 'Dame',
      similar_to: 'Right Turn',
      bar_counts: 8,
      instructions_follower: 'Follow the lead through the turn.',
      instructions_lead: 'Lead the turn effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 39,
      style_id: 1,
      name: 'Mata La cucarcha',
      level: 'Beginner',
      synonyms: 'Kill the Cockroach',
      translation: 'Mata La Cucaracha',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Rhythmic motion',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Follow the rhythmic steps.',
      instructions_lead: 'Lead the rhythm clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 40,
      style_id: 1,
      name: 'Miami',
      level: 'Beginner',
      synonyms: 'N/A',
      translation: 'Miami',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic position',
      contains: 'Miami-style motion',
      based_on: 'Basic Step',
      similar_to: 'Guapea',
      bar_counts: 4,
      instructions_follower: 'Follow the Miami steps.',
      instructions_lead: 'Guide through the Miami style.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 41,
      style_id: 1,
      name: 'Mujeres Izquierda / Derecha',
      level: 'Beginner',
      synonyms: 'Ladies Left / Right',
      translation: 'Mujeres Izquierda / Derecha',
      move_type: 'Turn',
      rueda_sign: 'N/A',
      starts_with: 'Begin with a basic step',
      contains: 'Left and right turns for ladies',
      based_on: 'Basic Step',
      similar_to: 'Ladies Right Turn',
      bar_counts: 8,
      instructions_follower: "Follow the lead's direction.",
      instructions_lead: 'Guide the turns effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 42,
      style_id: 1,
      name: 'Ocho',
      level: 'Beginner',
      synonyms: 'Figure Eight',
      translation: 'Ocho',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Begin in closed position',
      contains: 'Figure-eight movement',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 8,
      instructions_follower: 'Follow the figure-eight pattern.',
      instructions_lead: 'Lead the figure-eight clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 43,
      style_id: 1,
      name: "Pa'Ti Pa'Mi",
      level: 'Beginner',
      synonyms: 'For You For Me',
      translation: "Pa'Ti Pa'Mi",
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Back and forth motion',
      based_on: 'Basic Step',
      similar_to: 'Guapea',
      bar_counts: 8,
      instructions_follower: 'Follow the back-and-forth movement.',
      instructions_lead: 'Guide the steps effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 44,
      style_id: 1,
      name: 'Para Abajo',
      level: 'Beginner',
      synonyms: 'Go Down',
      translation: 'Para Abajo',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Begin from a basic position',
      contains: 'Downward motion',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Follow the downward motion.',
      instructions_lead: 'Lead the downward steps clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 45,
      style_id: 1,
      name: 'Para El Medio',
      level: 'Beginner',
      synonyms: 'To the Middle',
      translation: 'Para El Medio',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Initiate with a basic step',
      contains: 'Middle positioning',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Follow the middle position.',
      instructions_lead: 'Lead the movement to the center.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 46,
      style_id: 1,
      name: 'Policia',
      level: 'Beginner',
      synonyms: 'Police',
      translation: 'Policía',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start with a basic step',
      contains: 'Rhythmic policing motion',
      based_on: 'Basic Step',
      similar_to: 'Mata La cucarcha',
      bar_counts: 4,
      instructions_follower: 'Follow the policing rhythm.',
      instructions_lead: 'Guide through the policing steps.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 47,
      style_id: 1,
      name: 'Principe bueno',
      level: 'Beginner',
      synonyms: 'Good Prince',
      translation: 'Príncipe Bueno',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin from closed position',
      contains: 'Good prince moves',
      based_on: 'Basic Step',
      similar_to: 'Festival Principe Bueno Malo',
      bar_counts: 8,
      instructions_follower: 'Follow the good prince movements.',
      instructions_lead: 'Guide the movements effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 48,
      style_id: 1,
      name: 'Principe malo',
      level: 'Beginner',
      synonyms: 'Bad Prince',
      translation: 'Príncipe Malo',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Begin from closed position',
      contains: 'Bad prince moves',
      based_on: 'Basic Step',
      similar_to: 'Festival Principe Bueno Malo',
      bar_counts: 8,
      instructions_follower: 'Follow the bad prince movements.',
      instructions_lead: 'Guide the movements clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 49,
      style_id: 1,
      name: 'Taro',
      level: 'Beginner',
      synonyms: 'N/A',
      translation: 'Taro',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from basic position',
      contains: 'Taro-style movement',
      based_on: 'Basic Step',
      similar_to: 'Basic Steps',
      bar_counts: 4,
      instructions_follower: 'Follow the Taro movements.',
      instructions_lead: 'Guide the Taro style clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 50,
      style_id: 1,
      name: 'Taro de Mentira',
      level: 'Beginner',
      synonyms: 'Fake Taro',
      translation: 'Taro de Mentira',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from basic position',
      contains: 'Fake Taro movement',
      based_on: 'Basic Step',
      similar_to: 'Taro',
      bar_counts: 4,
      instructions_follower: 'Follow the fake Taro style.',
      instructions_lead: 'Lead the fake movements clearly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 51,
      style_id: 1,
      name: 'Taro Para Afuera',
      level: 'Beginner',
      synonyms: 'Taro Outward',
      translation: 'Taro Para Afuera',
      move_type: 'Basic',
      rueda_sign: 'N/A',
      starts_with: 'Start from basic position',
      contains: 'Outward Taro motion',
      based_on: 'Basic Step',
      similar_to: 'Taro',
      bar_counts: 4,
      instructions_follower: 'Follow the outward Taro movement.',
      instructions_lead: 'Guide the outward style effectively.',
      source: 'Salsayo',
      variations: 'N/A',
    },
    {
      id: 52,
      style_id: 1,
      name: 'Triple Play',
      level: 'Beginner',
      synonyms: 'Triple Combination',
      translation: 'Triple Play',
      move_type: 'Combination',
      rueda_sign: 'N/A',
      starts_with: 'Start from a basic step',
      contains: 'Three-part movement',
      based_on: 'Basic Step',
      similar_to: 'Doble Play',
      bar_counts: 8,
      instructions_follower: 'Follow through the three-part motion.',
      instructions_lead: 'Lead the triple movement smoothly.',
      source: 'Salsayo',
      variations: 'N/A',
    },
  ])
}
