/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('dance_moves').del()
  await knex('dance_moves').insert([
    {
      id: 1,
      name: 'Adios',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 2,
      name: 'Adios con la hermana',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 3,
      name: 'Adios con la familia',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 4,
      name: 'Adios con la prima',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 4,
      name: 'El Dos',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 5,
      name: 'Pa ti Pa mi',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 6,
      name: 'Setenta',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 7,
      name: 'La Montaña',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 8,
      name: 'Enchufla Doble Quedate',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 9,
      name: 'Sombrero con Coca Cola',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 10,
      name: 'Sombrero con Mambo',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 11,
      name: 'El Dedo',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 12,
      name: 'Vacilala',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 13,
      name: 'Vacilala y Dame',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 14,
      name: 'Sombrero (with tap)',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 15,
      name: 'Setenta (with tap)',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 16,
      name: 'La Montaña',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 17,
      name: 'Corona',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 18,
      name: 'Corona Doble',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 19,
      name: 'El Siete',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 20,
      name: 'El Siete con Coca Cola',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 21,
      name: 'Balcero',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 22,
      name: 'Enchufla Doble Complicado',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 23,
      name: 'Ochenta',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 24,
      name: 'Paseala',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 25,
      name: 'Paseala (por abajo y por arriba)',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 26,
      name: 'Sententa y Siete',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 27,
      name: 'Tocale a T',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 28,
      name: 'Evelyn',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 29,
      name: 'Evelyn con Coca Cola',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 30,
      name: 'Uno con dos',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 31,
      name: 'Cuban Sync',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 32,
      name: 'Setenta con gancho',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
    {
      id: 33,
      name: 'Sententa complicado',
      level: 'Improvers',
      synonymns: 'n/a',
      translation: 'n/a',
      move_type: 'Follow/Lead Technique',
      rueda_sign: 'n/a',
      starts_with: 'Basic',
      contains: 'Salsa on 1 basic',
      similar_to: 'Closed hold',
      bar_counts: 2,
      source: '',
      variations: 'n/a',
    },
  ])
}
